

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Loan_Pay : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Loan_Pay entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Loan_Pay()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Loan_Pay(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Loan_Pay> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Loan_Pay.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Loan_Pay_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Loan_Pay_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int amount_paid
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.amount_paid);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.amount_paid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_paid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_paid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void amount_paid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime paid_date
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.paid_date);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.paid_date, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paid_date_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paid_date_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paid_date_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Loan Loan
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Loan_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Loan_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Loan_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Customer Customer
        {
            get
            {
                return global::LightSwitchApplication.Loan_Pay.DetailsClass.GetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer);
            }
            set
            {
                global::LightSwitchApplication.Loan_Pay.DetailsClass.SetValue(this, global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customer_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Loan_Pay,
                global::LightSwitchApplication.Loan_Pay.DetailsClass,
                global::LightSwitchApplication.Loan_Pay.DetailsClass.IImplementation,
                global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>.Entry
                __Loan_PayEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>.Entry(
                    global::LightSwitchApplication.Loan_Pay.DetailsClass.__Loan_Pay_CreateNew,
                    global::LightSwitchApplication.Loan_Pay.DetailsClass.__Loan_Pay_Created,
                    global::LightSwitchApplication.Loan_Pay.DetailsClass.__Loan_Pay_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Loan_Pay __Loan_Pay_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Loan_Pay> es)
            {
                return new global::LightSwitchApplication.Loan_Pay(es);
            }
            private static void __Loan_Pay_Created(global::LightSwitchApplication.Loan_Pay e)
            {
                e.Loan_Pay_Created();
            }
            private static bool __Loan_Pay_AllowSaveWithErrors(global::LightSwitchApplication.Loan_Pay e)
            {
                bool result = false;
                e.Loan_Pay_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int> amount_paid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.amount_paid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime> paid_date
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.paid_date) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan> Loan
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer> Customer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new int amount_paid { get; set; }
                new global::System.DateTime paid_date { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Loan { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Customer { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Entry
                    amount_paid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Entry(
                        "amount_paid",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._amount_paid_OnValueChanged);
                private static void _amount_paid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._amount_paid, sf);
                }
                private static bool _amount_paid_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.amount_paid_IsReadOnly(ref result);
                    return result;
                }
                private static void _amount_paid_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.amount_paid_Validate(r);
                }
                private static int _amount_paid_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.amount_paid;
                }
                private static void _amount_paid_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, int v)
                {
                    d.ImplementationEntity.amount_paid = v;
                }
                private static void _amount_paid_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.amount_paid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime>.Entry
                    paid_date = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime>.Entry(
                        "paid_date",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._paid_date_OnValueChanged);
                private static void _paid_date_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._paid_date, sf);
                }
                private static bool _paid_date_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.paid_date_IsReadOnly(ref result);
                    return result;
                }
                private static void _paid_date_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.paid_date_Validate(r);
                }
                private static global::System.DateTime _paid_date_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.paid_date;
                }
                private static void _paid_date_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.paid_date = global::LightSwitchApplication.Loan_Pay.DetailsClass.TruncateDate(v);
                }
                private static void _paid_date_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.paid_date_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan>.Entry
                    Loan = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan>.Entry(
                        "Loan",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_GetCoreImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_Refresh,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Loan_OnValueChanged);
                private static void _Loan_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._Loan, sf);
                }
                private static bool _Loan_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.Loan_IsReadOnly(ref result);
                    return result;
                }
                private static void _Loan_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Loan_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Loan_GetCoreImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.Loan;
                }
                private static global::LightSwitchApplication.Loan _Loan_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Loan, global::LightSwitchApplication.Loan.DetailsClass>(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan, ref d._Loan);
                }
                private static void _Loan_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, global::LightSwitchApplication.Loan v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan, ref d._Loan, (i, ev) => i.Loan = ev, v);
                }
                private static void _Loan_Refresh(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Loan, ref d._Loan);
                }
                private static void _Loan_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.Loan_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customer",
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_Stub,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_ComputeIsReadOnly,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_Validate,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_GetCoreImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_GetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_SetImplementationValue,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_Refresh,
                        global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties._Customer_OnValueChanged);
                private static void _Customer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Loan_Pay.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.Loan_Pay.DetailsClass d, object sf)
                {
                    c(d, ref d._Customer, sf);
                }
                private static bool _Customer_ComputeIsReadOnly(global::LightSwitchApplication.Loan_Pay e)
                {
                    bool result = false;
                    e.Customer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Customer_Validate(global::LightSwitchApplication.Loan_Pay e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Customer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Customer_GetCoreImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.ImplementationEntity.Customer;
                }
                private static global::LightSwitchApplication.Customer _Customer_GetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Customer, global::LightSwitchApplication.Customer.DetailsClass>(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer, ref d._Customer);
                }
                private static void _Customer_SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass d, global::LightSwitchApplication.Customer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer, ref d._Customer, (i, ev) => i.Customer = ev, v);
                }
                private static void _Customer_Refresh(global::LightSwitchApplication.Loan_Pay.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Loan_Pay.DetailsClass.PropertySetProperties.Customer, ref d._Customer);
                }
                private static void _Customer_OnValueChanged(global::LightSwitchApplication.Loan_Pay e)
                {
                    e.Customer_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, int>.Data _amount_paid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::System.DateTime>.Data _paid_date;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Loan>.Data _Loan;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Loan_Pay, global::LightSwitchApplication.Loan_Pay.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customer;
            
        }
    
        #endregion
    }
    
    #endregion
}
