//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class AddCustomer
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private AddCustomer() : base("LightSwitchApplication:AddCustomer")
        {
            global::LightSwitchApplication.AddCustomer.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static AddCustomer CreateInstance()
        {
            return new global::LightSwitchApplication.AddCustomer(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddCustomer_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Table1ItemProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Table1Item Table1ItemProperty
        {
            get 
            {
                return global::LightSwitchApplication.AddCustomer.DetailsClass.GetValue(this, global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties.Table1ItemProperty);
            }
            set
            {
                global::LightSwitchApplication.AddCustomer.DetailsClass.SetValue(this, global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties.Table1ItemProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1ItemProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySet, global::LightSwitchApplication.AddCustomer.DetailsClass.CommandSet, global::LightSwitchApplication.AddCustomer.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties.Table1ItemProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>.Entry
                __AddCustomerEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>.Entry(
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeSavingEvent,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeSavedEvent,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeClosingEvent,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeCreated,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeActivated,
                    global::LightSwitchApplication.AddCustomer.DetailsClass.__AddCustomer_InvokeSaveErrorEvent);
            private static void __AddCustomer_InvokeInitializeDataWorkspace(global::LightSwitchApplication.AddCustomer s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.AddCustomer_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __AddCustomer_InvokeSavingEvent(global::LightSwitchApplication.AddCustomer s)
            {
                bool handled = false;
                s.AddCustomer_Saving(ref handled);
                return handled;
            }
            private static void __AddCustomer_InvokeSavedEvent(global::LightSwitchApplication.AddCustomer s)
            {
                s.AddCustomer_Saved();
            }
            private static bool __AddCustomer_InvokeClosingEvent(global::LightSwitchApplication.AddCustomer s)
            {
                bool cancel = false;
                s.AddCustomer_Closing(ref cancel);
                return cancel;
            }
            private static void __AddCustomer_InvokeCreated(global::LightSwitchApplication.AddCustomer s)
            {
                s.AddCustomer_Created();
            }
            private static void __AddCustomer_InvokeActivated(global::LightSwitchApplication.AddCustomer s)
            {
                s.AddCustomer_Activated();
            }
            private static bool __AddCustomer_InvokeSaveErrorEvent(global::LightSwitchApplication.AddCustomer s, global::System.Exception ex)
            {
                bool handled = false;
                s.AddCustomer_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.AddCustomer.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.AddCustomer.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1ItemProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item> Table1ItemProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>)base.GetItem(global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties.Table1ItemProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1ItemProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1ItemProperty",
                        false,
                        global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties._Table1ItemProperty_Stub,
                        global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties._Table1ItemProperty_Validate,
                        global::LightSwitchApplication.AddCustomer.DetailsClass.PropertySetProperties._Table1ItemProperty_OnValueChanged);
                private static void _Table1ItemProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AddCustomer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.AddCustomer, global::LightSwitchApplication.AddCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.AddCustomer.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1ItemProperty, sf);
                }
                private static void _Table1ItemProperty_Validate(global::LightSwitchApplication.AddCustomer s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Table1ItemProperty_Validate(r);
                }
                private static void _Table1ItemProperty_OnValueChanged(global::LightSwitchApplication.AddCustomer s)
                {
                    s.Table1ItemProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SearchCustomer
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchCustomer() : base("LightSwitchApplication:SearchCustomer")
        {
            global::LightSwitchApplication.SearchCustomer.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchCustomer CreateInstance()
        {
            return new global::LightSwitchApplication.SearchCustomer(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchCustomer_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Table1Items_SelectionChanged();

        partial void Table1Items_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Table1Items visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Table1Item> Table1Items
        {
            get
            {
                return global::LightSwitchApplication.SearchCustomer.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties.Table1Items);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySet, global::LightSwitchApplication.SearchCustomer.DetailsClass.CommandSet, global::LightSwitchApplication.SearchCustomer.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>.Entry
                __SearchCustomerEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeCreated,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeActivated,
                    global::LightSwitchApplication.SearchCustomer.DetailsClass.__SearchCustomer_InvokeSaveErrorEvent);
            private static void __SearchCustomer_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchCustomer s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchCustomer_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchCustomer_InvokeSavingEvent(global::LightSwitchApplication.SearchCustomer s)
            {
                bool handled = false;
                s.SearchCustomer_Saving(ref handled);
                return handled;
            }
            private static void __SearchCustomer_InvokeSavedEvent(global::LightSwitchApplication.SearchCustomer s)
            {
                s.SearchCustomer_Saved();
            }
            private static bool __SearchCustomer_InvokeClosingEvent(global::LightSwitchApplication.SearchCustomer s)
            {
                bool cancel = false;
                s.SearchCustomer_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchCustomer_InvokeCreated(global::LightSwitchApplication.SearchCustomer s)
            {
                s.SearchCustomer_Created();
            }
            private static void __SearchCustomer_InvokeActivated(global::LightSwitchApplication.SearchCustomer s)
            {
                s.SearchCustomer_Activated();
            }
            private static bool __SearchCustomer_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchCustomer s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchCustomer_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchCustomer.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchCustomer.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Table1ItemsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>)base.GetItem(global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties.Table1Items);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items",
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_Stub,
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_Validate,
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_CreateQuery,
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_SelectionChanged,
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_OnCollectionChanged,
                        global::LightSwitchApplication.SearchCustomer.DetailsClass.PropertySetProperties._Table1Items_OnLoaded);
                private static void _Table1Items_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchCustomer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchCustomer, global::LightSwitchApplication.SearchCustomer.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.SearchCustomer.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items, sf);
                }
                private static void _Table1Items_Validate(global::LightSwitchApplication.SearchCustomer s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Table1Items_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Table1Items_CreateQuery(global::LightSwitchApplication.SearchCustomer.DetailsClass d, object[] args)
                {
                    return d.Table1ItemsQuery();
                }
                private static void _Table1Items_SelectionChanged(global::LightSwitchApplication.SearchCustomer s)
                {
                    s.Table1Items_SelectionChanged();
                }
                private static void _Table1Items_OnCollectionChanged(global::LightSwitchApplication.SearchCustomer s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Table1Items_Changed(e);
                }
                private static void _Table1Items_OnLoaded(global::LightSwitchApplication.SearchCustomer s, bool succeeded)
                {
                    s.Table1Items_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CustomerList
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CustomerList() : base("LightSwitchApplication:CustomerList")
        {
            global::LightSwitchApplication.CustomerList.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CustomerList CreateInstance()
        {
            return new global::LightSwitchApplication.CustomerList(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomerList_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Table1Items_SelectionChanged();

        partial void Table1Items_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Table1Items visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Table1Item> Table1Items
        {
            get
            {
                return global::LightSwitchApplication.CustomerList.DetailsClass.GetValue(this, global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties.Table1Items);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Table1Items_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.CustomerList.DetailsClass.PropertySet, global::LightSwitchApplication.CustomerList.DetailsClass.CommandSet, global::LightSwitchApplication.CustomerList.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>.Entry
                __CustomerListEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>.Entry(
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeSavingEvent,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeSavedEvent,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeClosingEvent,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeCreated,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeActivated,
                    global::LightSwitchApplication.CustomerList.DetailsClass.__CustomerList_InvokeSaveErrorEvent);
            private static void __CustomerList_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CustomerList s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CustomerList_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CustomerList_InvokeSavingEvent(global::LightSwitchApplication.CustomerList s)
            {
                bool handled = false;
                s.CustomerList_Saving(ref handled);
                return handled;
            }
            private static void __CustomerList_InvokeSavedEvent(global::LightSwitchApplication.CustomerList s)
            {
                s.CustomerList_Saved();
            }
            private static bool __CustomerList_InvokeClosingEvent(global::LightSwitchApplication.CustomerList s)
            {
                bool cancel = false;
                s.CustomerList_Closing(ref cancel);
                return cancel;
            }
            private static void __CustomerList_InvokeCreated(global::LightSwitchApplication.CustomerList s)
            {
                s.CustomerList_Created();
            }
            private static void __CustomerList_InvokeActivated(global::LightSwitchApplication.CustomerList s)
            {
                s.CustomerList_Activated();
            }
            private static bool __CustomerList_InvokeSaveErrorEvent(global::LightSwitchApplication.CustomerList s, global::System.Exception ex)
            {
                bool handled = false;
                s.CustomerList_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CustomerList.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CustomerList.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CustomerList.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Table1ItemsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Table1Items;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item>.Data _Table1Items;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item> Table1Items
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item>)base.GetItem(global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties.Table1Items);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry
                    Table1Items = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item>.Entry(
                        "Table1Items",
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_Stub,
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_Validate,
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_CreateQuery,
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_SelectionChanged,
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_OnCollectionChanged,
                        global::LightSwitchApplication.CustomerList.DetailsClass.PropertySetProperties._Table1Items_OnLoaded);
                private static void _Table1Items_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomerList.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomerList, global::LightSwitchApplication.CustomerList.DetailsClass, global::LightSwitchApplication.Table1Item>.Data> c, global::LightSwitchApplication.CustomerList.DetailsClass d, object sf)
                {
                    c(d, ref d._Table1Items, sf);
                }
                private static void _Table1Items_Validate(global::LightSwitchApplication.CustomerList s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Table1Items_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Table1Items_CreateQuery(global::LightSwitchApplication.CustomerList.DetailsClass d, object[] args)
                {
                    return d.Table1ItemsQuery();
                }
                private static void _Table1Items_SelectionChanged(global::LightSwitchApplication.CustomerList s)
                {
                    s.Table1Items_SelectionChanged();
                }
                private static void _Table1Items_OnCollectionChanged(global::LightSwitchApplication.CustomerList s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Table1Items_Changed(e);
                }
                private static void _Table1Items_OnLoaded(global::LightSwitchApplication.CustomerList s, bool succeeded)
                {
                    s.Table1Items_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
